"""Claim-safe PK/hERG parameter ontology.

The ontology separates causal free energies and rates from boundary
conditions, direct observations, derived functionals, diagnostics, and
observation-model nuisance parameters.  A row is a causal node or transition,
not an instruction to fit one scalar coefficient per compound.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

import pandas as pd


@dataclass(frozen=True)
class ParameterConcept:
    domain: str
    order: int
    parameter_id: str
    parameter_name: str
    parameter_class: str
    mathematical_object: str
    distinct_causal_node: str
    endpoint_roles: str
    parent_parameter_ids: str
    current_internal_support: str
    permissible_role_now: str
    measurement_or_calculation: str
    hidden_variables_and_confounders: str
    decisive_falsification: str
    required_resource: str
    novelty_status: str
    novelty_contribution: str


_PK: tuple[ParameterConcept, ...] = (
    ParameterConcept(
        "pk",
        1,
        "pk_dose_formulation_input",
        "dose–formulation input u_r(t)",
        "boundary_condition",
        "route-specific input function",
        "material delivered to the IV or gastrointestinal system",
        "all rat PK endpoints",
        "",
        "dose and route only; formulation metadata absent",
        "context_only",
        "recorded dose, route, dosing duration, salt/solid form, vehicle, and dose recovery",
        "actual delivered dose, release kinetics, precipitation, particle size",
        "formulation-matched replication and dose recovery",
        "additional_metadata_and_experiment",
        "established",
        "none; required boundary condition",
    ),
    ParameterConcept(
        "pk",
        2,
        "pk_dissolution_rate",
        "dissolution and aggregate-to-monomer rates",
        "fundamental_rate",
        "time- and pH-dependent rate constants",
        "solid/aggregate material becoming free dissolved monomer",
        "PO AUC, Cmax, Tmax",
        "pk_dose_formulation_input",
        "none",
        "blocked",
        "kinetic solubility, dissolution, aggregate separation, and time-resolved free monomer",
        "solid form, particle size, bile, pH, colloids, formulation",
        "mass-balanced time course under formulation and pH perturbation",
        "additional_experiment",
        "established",
        "undermeasured boundary-to-access node in large molecules",
    ),
    ParameterConcept(
        "pk",
        3,
        "pk_precipitation_rate",
        "supersaturation decay and precipitation rate",
        "fundamental_rate",
        "state-transition rate",
        "loss of dissolved monomer before barrier crossing",
        "PO AUC, Cmax, Tmax",
        "pk_dissolution_rate",
        "none",
        "blocked",
        "supersaturation/precipitation time course with recovery and solid-state analysis",
        "nucleation, bile components, agitation, formulation, assay surfaces",
        "change supersaturation lifetime while holding nominal dose constant",
        "additional_experiment",
        "established",
        "separates luminal loss from membrane resistance",
    ),
    ParameterConcept(
        "pk",
        4,
        "pk_free_monomer_activity",
        "free-monomer thermodynamic activity",
        "direct_process_observable",
        "time- and pH-dependent activity/concentration",
        "molecular material actually available to a barrier",
        "PO AUC, Cmax, Tmax",
        "pk_dissolution_rate;pk_precipitation_rate",
        "none",
        "blocked",
        "separation-aware thermodynamic/kinetic solubility and analytical mass balance",
        "aggregation, nonspecific binding, activity coefficient, recovery",
        "orthogonal free-monomer methods agree within prespecified error",
        "additional_experiment",
        "established",
        "prevents nominal solubility from masquerading as delivered free concentration",
    ),
    ParameterConcept(
        "pk",
        5,
        "pk_microstate_free_energy",
        "chemical-state free energies ΔG_s(pH, environment)",
        "fundamental_free_energy",
        "microstate free-energy surface",
        "protonation/tautomer states available in each environment",
        "PO absorption, distribution, hERG-linked exposure",
        "",
        "macroscopic pKa summaries only",
        "hypothesis_and_uncertainty_only",
        "microscopic pKa/tautomer evidence or validated constant-pH free-energy calculation",
        "coupled ionization, ionic strength, tautomer assignment, interface pKa shift",
        "pH-dependent state populations and matched permeability/solubility directions",
        "hpc_and_additional_experiment",
        "established",
        "foundation for rare-state flux; not novel by itself",
    ),
    ParameterConcept(
        "pk",
        6,
        "pk_microstate_exchange_rate",
        "microstate exchange rates k_ss′",
        "fundamental_rate",
        "chemical-state transition generator",
        "whether charge/tautomer switching occurs within barrier residence time",
        "PO absorption and access-linked exposure",
        "pk_microstate_free_energy",
        "none",
        "blocked",
        "constant-pH kinetics, pH-jump, or spectroscopic exchange",
        "proton donors, interface shifts, non-Markovian coupling to conformation",
        "perturb pH and residence time; onset/flux must follow the predicted kinetic regime",
        "hpc_and_additional_experiment",
        "adapted",
        "cross-process coupling of state switching to barrier residence is potentially novel",
    ),
    ParameterConcept(
        "pk",
        7,
        "pk_conformer_basin_free_energy",
        "environment-conditioned conformational basin free energies",
        "fundamental_free_energy",
        "free energies of metastable basins by environment",
        "conformations stable in water, interface, membrane, and tissue-like media",
        "PO absorption and distribution",
        "pk_microstate_free_energy",
        "none",
        "blocked",
        "NMR/NAMFIS plus converged enhanced sampling",
        "force field, basin definition, missing slow modes, environment composition",
        "independent replicas and solvent-sensitive experimental populations agree",
        "hpc_and_additional_experiment",
        "established",
        "none; equilibrium component of the transition framework",
    ),
    ParameterConcept(
        "pk",
        8,
        "pk_conformer_transition_rate",
        "conformational transition rates, MFPT, committor, reactive flux",
        "fundamental_rate",
        "transition matrix plus path functionals",
        "formation of a transport-competent basin before biological residence ends",
        "especially PO Cmax and Tmax; also PO AUC",
        "pk_conformer_basin_free_energy",
        "none",
        "blocked",
        "replicated enhanced sampling/transition networks and exchange kinetics",
        "reaction coordinate, lag time, hidden modes, state definition",
        "implied-timescale, Chapman–Kolmogorov, seed, and matched-pair direction tests",
        "hpc_and_additional_experiment",
        "adapted",
        "reactive-flux-weighted exposure and biological-timescale gating are central candidate novelties",
    ),
    ParameterConcept(
        "pk",
        9,
        "pk_site_desolvation_compensation",
        "site-resolved desolvation and compensation free energies",
        "fundamental_free_energy",
        "per-site hydration loss minus gained interactions",
        "energetic cost of moving donors, acceptors, and charge into a new environment",
        "membrane crossing and tissue partition",
        "pk_microstate_free_energy;pk_conformer_basin_free_energy",
        "none",
        "blocked",
        "hydration free energy/water residence plus gained IMHB, lipid, or receptor interactions",
        "water model, protonation, non-unique energy decomposition",
        "donor/acceptor-selective matched edits and NMR/flux direction",
        "hpc_and_additional_experiment",
        "adapted",
        "replaces SASA/count composites with a process-specific energy balance",
    ),
    ParameterConcept(
        "pk",
        10,
        "pk_membrane_pmf",
        "state-specific membrane PMF W_s(z)",
        "fundamental_free_energy",
        "free-energy profile along validated membrane coordinates",
        "entry, interfacial trapping, core crossing, and release energetics",
        "PO absorption",
        "pk_microstate_free_energy;pk_conformer_transition_rate",
        "none",
        "blocked",
        "state-specific enhanced sampling with global/local coordinate comparison",
        "patch size, deformation, leaflet asymmetry, coordinate hysteresis",
        "forward/reverse, leaflet, patch, force-field, and PMF-drift gates",
        "hpc",
        "established",
        "project-specific entry/core/release bottleneck attribution is adapted",
    ),
    ParameterConcept(
        "pk",
        11,
        "pk_membrane_diffusivity",
        "state-specific membrane diffusivity D_s(z)",
        "fundamental_transport_coefficient",
        "position-dependent diffusion profile",
        "mobility through each region of the membrane",
        "PO absorption",
        "pk_membrane_pmf",
        "none",
        "blocked",
        "restrained trajectory time-correlation analysis with uncertainty",
        "restraint strength, memory, coordinate quality, local equilibration",
        "block-length and replica stability plus experimental temperature dependence",
        "hpc",
        "established",
        "required with PMF; a barrier alone is not permeability",
    ),
    ParameterConcept(
        "pk",
        12,
        "pk_effective_permeability",
        "microstate-weighted effective permeability",
        "derived_mechanistic_functional",
        "inverse solubility-diffusion resistance weighted across states",
        "net passive flux after integrating state population, PMF, and diffusivity",
        "PO absorption",
        "pk_microstate_free_energy;pk_membrane_pmf;pk_membrane_diffusivity",
        "none",
        "blocked",
        "derive from converged parents and validate using PAMPA/liposomes at multiple pH values",
        "exponential PMF sensitivity, rare states, unstirred layer",
        "parent convergence plus pH-dependent experimental flux and recovery",
        "hpc_and_additional_experiment",
        "established",
        "rare-state flux integration is important but not novel by itself",
    ),
    ParameterConcept(
        "pk",
        13,
        "pk_enterocyte_competing_rates",
        "enterocyte competing transport and loss rates",
        "fundamental_rate",
        "competing transition/absorbing-state generator",
        "basolateral escape versus efflux, re-entry, sequestration, and gut loss",
        "PO AUC, Cmax, Tmax",
        "pk_free_monomer_activity;pk_effective_permeability",
        "none",
        "blocked",
        "A→B/B→A time courses, recovery, transporter inhibitors, gut stability",
        "saturation, unstirred layer, binding, precipitation, expression",
        "jointly reproduce flux, recovery, concentration, and inhibitor response",
        "additional_experiment",
        "adapted",
        "absorbing-state integration makes efflux a causal branch rather than one scalar ratio",
    ),
    ParameterConcept(
        "pk",
        14,
        "pk_hepatic_disposition_rates",
        "unbound hepatic uptake, metabolism, efflux, and biliary rates",
        "fundamental_rate",
        "organ-process rate system",
        "hepatic extraction and first-pass/systemic loss",
        "IV and PO AUC; concentration-time profiles",
        "",
        "four compounds have partial proxies",
        "blocked_for_mechanistic_fit",
        "hepatocyte/microsome CLint,u, uptake inhibitors, fu,inc, and mass balance",
        "protein-mediated uptake, abundance, transporter/enzyme coupling",
        "same-compound perturbation must close hepatic mass balance",
        "additional_experiment",
        "established",
        "mechanistic integration is established; current data are insufficient",
    ),
    ParameterConcept(
        "pk",
        15,
        "pk_plasma_blood_partition",
        "plasma unbound fraction and blood:plasma partition",
        "direct_process_observable",
        "measured equilibrium ratios with uncertainty",
        "free circulating concentration and blood-cell partition",
        "distribution, clearance, unbound exposure",
        "",
        "four compounds have partial protein-binding evidence",
        "blocked_for_population_model",
        "orthogonal PPB/fu and blood:plasma measurements",
        "nonspecific binding, concentration dependence, assay recovery",
        "orthogonal methods and concentration series agree",
        "additional_experiment",
        "established",
        "required exposure constraint",
    ),
    ParameterConcept(
        "pk",
        16,
        "pk_tissue_partition_exchange",
        "unbound tissue partition and exchange rates",
        "fundamental_free_energy_and_rate",
        "tissue transfer free energies plus exchange kinetics",
        "tissue distribution, sequestration, and return to plasma",
        "Vdss and concentration-time shape",
        "pk_plasma_blood_partition",
        "none",
        "blocked",
        "tissue Kp,uu, subcellular partition, and profile-informed exchange",
        "lysosomal trapping, membrane binding, saturation, perfusion limits",
        "orthogonal tissue data and identifiable profile model",
        "additional_experiment_and_hpc",
        "established",
        "distinguishes thermodynamic partition from kinetic equilibration",
    ),
    ParameterConcept(
        "pk",
        17,
        "pk_renal_extrahepatic_rates",
        "renal and extrahepatic elimination rates",
        "fundamental_rate",
        "filtration, secretion, reabsorption, and degradation rates",
        "nonhepatic systemic loss",
        "IV/PO AUC and profiles",
        "pk_plasma_blood_partition",
        "none",
        "blocked",
        "urine/bile recovery, filtration and transporter perturbation",
        "urine pH, fu, transporters, unmeasured degradation",
        "mass balance and inhibitor/urine-pH perturbation",
        "additional_experiment",
        "established",
        "required only if material in this series",
    ),
    ParameterConcept(
        "pk",
        18,
        "pk_rat_physiology",
        "rat physiological constants",
        "physiological_boundary_condition",
        "distributions of organ volumes, flows, and composition",
        "species/strain/sex context for mass balance",
        "all profile models",
        "",
        "species only",
        "context_only",
        "declared literature/experimental distributions stratified by strain, sex, and age",
        "strain, sex, age, disease, laboratory conditions",
        "sensitivity and external physiological consistency",
        "additional_metadata",
        "established",
        "not a molecular predictor",
    ),
    ParameterConcept(
        "pk",
        19,
        "pk_observation_model",
        "PK protocol and observation model",
        "observation_nuisance",
        "hierarchical sampling, censoring, and assay-error model",
        "maps latent concentrations to recorded samples without learning protocol as chemistry",
        "all rat PK endpoints",
        "",
        "dose/route present; strain, sex, formulation, matrix, LLOQ and raw samples absent",
        "blocked",
        "per-animal sample times, LLOQ/censoring, batch, protocol, and replicate identities",
        "source echoes, assay drift, missing-not-at-random advancement",
        "source/batch holdout, recovery simulation, and posterior predictive checks",
        "additional_data",
        "established",
        "essential inferential layer, not molecular novelty",
    ),
)


_HERG: tuple[ParameterConcept, ...] = (
    ParameterConcept(
        "herg",
        1,
        "herg_free_bath_concentration",
        "free bath concentration C_u(t)",
        "boundary_condition",
        "measured free concentration time course",
        "ligand activity presented to cells/channels",
        "all hERG endpoints",
        "",
        "nominal concentration only for some observations",
        "blocked",
        "analytical concentration with recovery, binding, precipitation, and depletion correction",
        "plastic/cell binding, precipitation, depletion, free fraction",
        "assay mass balance and concentration recovery",
        "additional_experiment",
        "established",
        "required boundary condition",
    ),
    ParameterConcept(
        "herg",
        2,
        "herg_ligand_microstate_free_energy",
        "ligand microstate free energies at assay conditions",
        "fundamental_free_energy",
        "microstate free-energy surface",
        "neutral access, cationic stabilization, and zwitterionic alternatives",
        "onset, potency, recovery",
        "",
        "macroscopic pKa summaries only",
        "hypothesis_and_uncertainty_only",
        "micro-pKa/tautomer measurements or validated constant-pH calculation",
        "local dielectric shift, coupled titration, ionic strength",
        "pH-dependent potency and membrane-access directions",
        "hpc_and_additional_experiment",
        "established",
        "component of the proposed access-to-binding coupling",
    ),
    ParameterConcept(
        "herg",
        3,
        "herg_microstate_switching_rate",
        "local microstate switching rate",
        "fundamental_rate",
        "chemical-state transition rate relative to residence time",
        "charge-gated conversion between access-competent and binding-competent states",
        "onset, potency, recovery",
        "herg_ligand_microstate_free_energy",
        "none",
        "blocked",
        "constant-pH kinetics or pH-jump/onset experiments",
        "interface protonation, coupled titration, membrane reservoir",
        "pH perturbation changes access/onset as preregistered",
        "hpc_and_additional_experiment",
        "potentially_novel_coupling",
        "large-molecule membrane/cavity residence coupled to protonation kinetics",
    ),
    ParameterConcept(
        "herg",
        4,
        "herg_membrane_access_rate",
        "membrane/channel-proximal access and escape rates",
        "fundamental_rate",
        "access/escape transitions and local activity",
        "reaching the channel cavity separately from binding",
        "onset and apparent IC50",
        "herg_free_bath_concentration;herg_ligand_microstate_free_energy",
        "none",
        "blocked",
        "membrane partition/recovery plus concentration-dependent onset",
        "lipid composition, interfacial trapping, monomer activity, rebinding",
        "partition/onset perturbation without corresponding affinity change",
        "hpc_and_additional_experiment",
        "adapted",
        "separating large-molecule access from stabilization is central",
    ),
    ParameterConcept(
        "herg",
        5,
        "herg_drug_free_gating_generator",
        "drug-free channel generator Q0(V,K,T)",
        "fundamental_rate",
        "voltage-, potassium-, and temperature-dependent gating matrix",
        "availability of closed/open/inactivated states under a protocol",
        "all dynamic hERG endpoints",
        "",
        "no voltage traces or protocol metadata",
        "blocked",
        "fit drug-free voltage-clamp currents across prespecified protocols",
        "cell line, construct, voltage history, K+, temperature",
        "reproduce held-out drug-free protocols and gating observables",
        "additional_experiment",
        "established",
        "required receptor-state boundary, not a molecular predictor",
    ),
    ParameterConcept(
        "herg",
        6,
        "herg_state_binding_free_energy",
        "receptor-state/microstate binding free energies",
        "fundamental_free_energy",
        "state- and pose-ensemble ΔG_bind",
        "stabilization after cavity access",
        "potency and state preference",
        "herg_ligand_microstate_free_energy;herg_drug_free_gating_generator",
        "none",
        "blocked",
        "matched-pair experiment plus converged receptor-state free energies",
        "pose, construct, state, protonation, retained waters, structural uncertainty",
        "cycle closure, state/pose stability, mutagenesis, and matched-pair direction",
        "hpc_and_additional_experiment",
        "established",
        "state-conditioned large-molecule application is adapted",
    ),
    ParameterConcept(
        "herg",
        7,
        "herg_association_rate",
        "state/microstate association rate k_on^sr",
        "fundamental_rate",
        "concentration-dependent association/access rate",
        "entry and recognition after channel availability",
        "onset and protocol-dependent potency",
        "herg_membrane_access_rate;herg_drug_free_gating_generator",
        "none",
        "blocked",
        "concentration-dependent onset under multiple voltage protocols",
        "diffusion, membrane enrichment, gating, state switching",
        "one rate system reproduces held-out concentration/protocol onset",
        "additional_experiment_and_hpc",
        "established",
        "must not be inferred from static IC50",
    ),
    ParameterConcept(
        "herg",
        8,
        "herg_dissociation_rate",
        "state/microstate dissociation rate k_off^sr",
        "fundamental_rate",
        "state-conditioned unbinding rate",
        "residence and recovery independent of association",
        "washout/recovery and protocol-dependent potency",
        "herg_state_binding_free_energy",
        "none",
        "blocked",
        "washout/recovery across exposure durations and voltage protocols",
        "rebinding, membrane reservoir, incomplete exchange",
        "consistent recovery across held-out washout protocols",
        "additional_experiment_and_hpc",
        "established",
        "must not be inferred from static IC50",
    ),
    ParameterConcept(
        "herg",
        9,
        "herg_trapping_escape_rate",
        "closure-state trapping and escape rates",
        "fundamental_rate",
        "drug-bound channel closure/escape transitions",
        "persistent occupancy distinct from slow ordinary dissociation",
        "trapping, recovery, persistent block",
        "herg_drug_free_gating_generator;herg_dissociation_rate",
        "none",
        "blocked",
        "trapping-selective voltage protocols with complete washout controls",
        "gating topology, membrane accumulation, incomplete washout",
        "trapping-selective protocol distinguishes the rate from k_off",
        "additional_experiment_and_hpc",
        "established",
        "large-molecule access/trapping coupling is adapted",
    ),
    ParameterConcept(
        "herg",
        10,
        "herg_protocol_integrated_occupancy",
        "protocol-integrated bound/trapped occupancy",
        "derived_mechanistic_functional",
        "continuous-time Markov occupancy/current prediction",
        "maps gating and drug rates to measured current inhibition",
        "current inhibition and apparent IC50",
        "herg_drug_free_gating_generator;herg_association_rate;herg_dissociation_rate;herg_trapping_escape_rate",
        "none",
        "blocked",
        "derive only from identifiable rates and reproduce multiple protocols",
        "model topology, practical identifiability, conductance observation",
        "simulation recovery plus held-out protocol prediction",
        "additional_experiment_and_hpc",
        "established",
        "protocol integration replaces a universal IC50 interpretation",
    ),
    ParameterConcept(
        "herg",
        11,
        "herg_receptor_state_definition",
        "receptor induced-fit/symmetry state definition",
        "structural_diagnostic",
        "discrete structural hypotheses and transitions",
        "defines alternative cavity/filter states without inventing a scalar score",
        "pose/state interpretation",
        "",
        "six raw coordinate hypotheses only",
        "hypothesis_library_only",
        "construct/map audit, separate preparation, replicate stability, and perturbation",
        "cryo-EM resolution, symmetry, construct, detergent, ion occupancy",
        "mutagenesis/state perturbation and replicate stability",
        "hpc_and_additional_experiment",
        "established_structural_precedent",
        "six-coordinate uncertainty treatment is adapted; no Y652 score is claimed",
    ),
    ParameterConcept(
        "herg",
        12,
        "herg_assay_observation_model",
        "hERG assay observation model",
        "observation_nuisance",
        "protocol/censoring/Hill/current-error likelihood",
        "maps latent state occupancy to recorded current under each assay",
        "all hERG observations",
        "",
        "endpoint/relation/concentration only; most protocol fields absent",
        "blocked",
        "cell, temperature, pH, K+, voltage waveform, duration, replicate, batch, and censoring",
        "protocol heterogeneity, Hill slope, free concentration, source effects",
        "protocol/source holdout and posterior predictive checks",
        "additional_data",
        "established",
        "prevents assay context from masquerading as chemistry",
    ),
    ParameterConcept(
        "herg",
        13,
        "herg_unbound_cardiac_exposure",
        "unbound cardiac exposure",
        "derived_cross_domain_functional",
        "Cmax,u or cardiac interstitial concentration profile",
        "links systemic exposure to intrinsic hERG liability",
        "exposure margin only",
        "pk_plasma_blood_partition;pk_tissue_partition_exchange",
        "no supportable unbound Cmax",
        "blocked",
        "derive from measured PK, fu, blood partition, and cardiac access",
        "active metabolites, PPB, tissue partition, temporal mismatch",
        "measured unbound exposure and protocol-compatible potency",
        "additional_experiment",
        "established",
        "safety integration only; never an input to intrinsic hERG potency",
    ),
)


ALLOWED_PARAMETER_CLASSES = {
    "boundary_condition",
    "direct_process_observable",
    "fundamental_free_energy",
    "fundamental_rate",
    "fundamental_transport_coefficient",
    "fundamental_free_energy_and_rate",
    "derived_mechanistic_functional",
    "derived_cross_domain_functional",
    "physiological_boundary_condition",
    "observation_nuisance",
    "structural_diagnostic",
}


def parameter_ontology_frame(domain: str | None = None) -> pd.DataFrame:
    """Return the final parameter modules, optionally restricted by domain."""

    records = [asdict(concept) for concept in (*_PK, *_HERG)]
    frame = pd.DataFrame(records)
    if domain is not None:
        frame = frame[frame["domain"].eq(domain)].copy()
    return frame.sort_values(["domain", "order"], kind="stable").reset_index(drop=True)


def validate_parameter_ontology(frame: pd.DataFrame | None = None) -> None:
    """Fail on ontology contradictions that could cause causal double counting."""

    table = parameter_ontology_frame() if frame is None else frame.copy()
    if table["parameter_id"].duplicated().any():
        raise ValueError("Parameter ontology IDs must be unique")
    unknown = sorted(set(table["parameter_class"]) - ALLOWED_PARAMETER_CLASSES)
    if unknown:
        raise ValueError(f"Unknown parameter classes: {unknown}")
    derived = table["parameter_class"].str.startswith("derived")
    if table.loc[derived, "parent_parameter_ids"].str.strip().eq("").any():
        raise ValueError("Every derived functional must declare its causal parents")
    if table["permissible_role_now"].str.contains("decision", case=False).any():
        raise ValueError("No current mechanistic parameter is decision-track eligible")


__all__ = [
    "ALLOWED_PARAMETER_CLASSES",
    "ParameterConcept",
    "parameter_ontology_frame",
    "validate_parameter_ontology",
]
